### ISSUE TITLE
substitute version number for placeholder string

### ISSUE THREAD

**Issue by hernandezurbina** [erocarrera/pydot#103] opened 2015-06-02 11:21 UTC
Hi, I'm trying to run this on OS X (10.9.5) and just right after typing "import pydot" I get the following error:
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydot/pydot.py", line 22, in <module>
    __version__ = '1.0.%d' % int( __revision__[21:-2] )
ValueError: invalid literal for int() with base 10: ''
Then, I tried to install using pip and everything seems right until I import again and get this error:
"Failed to import pydot. You must install pydot for `pydotprint` to work."
I have installed graphviz (0.4.4) and pyparsing (2.0.3). Can't figure out what might be the problem.

**Comment by sanujitsahoo** [comment] 2015-07-05 15:22
Try installing pydot from - https://github.com/nlhepler/pydot

**Comment by j123kaishichufa** [comment] 2016-01-07 10:06
on ubuntu-14,  I got the same error when installing  pydot from source code: python setup.py install.

**Comment by j123kaishichufa** [comment] 2016-01-07 10:08
but it works when trying apt-get install python-pydot

**Comment by artvandelay** [comment] 2016-02-09 06:00
Well, I think the problem is at line 20 in pydot.py  where the "$LastChangedRevision$" is somehow suppose to be set to a number while it's still a string. For my case (I just wanted to import it) I commented out line 20-22.
Not an ideal solution but does the trick for me

**Comment by johnyf** [comment] 2016-05-10 21:49
Indeed, this is caused by forming the version number by casting as `int` [a two-letter substring of `__revision__`](https://github.com/erocarrera/pydot/blob/5e903e15b27a57bf300560cbea90d772a092a9b3/pydot.py#L22). However, `__revision__` is the placeholder [`"$LastChangedRevision$"`](https://github.com/erocarrera/pydot/blob/5e903e15b27a57bf300560cbea90d772a092a9b3/pydot.py#L20), probably a remnant from SVN or something similar that was once replaced by a script or manually during the release procedure.

In any case, this issue doesn't arise in the released `pydot == 1.0.28`, because the string has been replaced one containing the version identifier. It will be fixed in the code.

**Comment by johnyf** [comment] 2016-05-11 00:45
Fixed by 8ca3077ece8be35bc1ba528a1d52bcc0a218fc5c.

**Closed by johnyf** 2016-05-11 00:45 UTC
Labels: bug
