### ISSUE TITLE
Can't install Pydot via pip on my ovh server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#87] opened 2015-04-13 15:16 UTC
```
What steps will reproduce the problem?
1. pip install pydot


Downloading/unpacking pydot
  HTTP error 403 while getting http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz (from https://pypi.python.org/simple/pydot/)
  Could not install requirement pydot because of error HTTP Error 403: Forbidden
Could not install requirement pydot because of HTTP error HTTP Error 403: 
Forbidden for URL http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz (from 
https://pypi.python.org/simple/pydot/)

This is very strange since it works on my local machine.


Please provide any additional information below.

Ubuntu 13.04/Python2.7(virtualenv, pip1.4.1)
similar issue: https://github.com/gak/pygooglechart/issues/18

```

Original issue reported on code.google.com by `sdia....@gmail.com` on 2 Dec 2013 at 6:48

**Comment by johnyf** [comment] 2016-05-10 21:40
This is caused by `pip` by default not fetching tarballs from outside PyPI, per [PEP 470](https://www.python.org/dev/peps/pep-0470/). The workaround is `pip install 'pydot==1.0.28' --allow-external pydot --allow-unverified pydot`, as noted in #93.

Should be fixed by #96.

**Closed by johnyf** 2016-05-10 21:40 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
